### ISSUE TITLE
Depending on Nd4j fails via bazel-deps but works in Maven

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/benchmark#75]
Trying to add the following maven artifact to `dependencies.yml`:

```
  org.nd4j:
    nd4j-native:
      version: "0.9.1"
      lang: java
```

leads to the following when calling `update.sh`:

```
✔ 11:58: ~/Documents/benchmark [java-metrics|●1✚ 8 …7⚑ 7]> ./dependencies/maven/update.sh 
INFO: Analysed target //dependencies/tools:bazel-deps (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //dependencies/tools:bazel-deps up-to-date:
  bazel-bin/dependencies/tools/bazel-deps.jar
  bazel-bin/dependencies/tools/bazel-deps
INFO: Elapsed time: 0.145s, Critical Path: 0.00s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
[main] ERROR MakeDeps - resolution and sha collection failed
java.lang.RuntimeException: no artifacts for org.nd4j:nd4j-backend-impls:pom:macosx-x86_64:0.9.1 found
	at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$com$github$johnynek$bazel_deps$CoursierResolver$$lookup$1$1$$anonfun$apply$7$$anonfun$apply$9.apply(CoursierResolver.scala:182)
	at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$com$github$johnynek$bazel_deps$CoursierResolver$$lookup$1$1$$anonfun$apply$7$$anonfun$apply$9.apply(CoursierResolver.scala:180)
	at coursier.util.Task$$anonfun$flatMap$extension$1$$anonfun$apply$1.apply(Task.scala:10)
	at coursier.util.Task$$anonfun$flatMap$extension$1$$anonfun$apply$1.apply(Task.scala:10)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The issue is reproduced minimally in a small repository at 
https://github.com/flyingsilverfin/bazel-vs-maven-nd4j-dependency

This is an issue on our end, since including the same artifact via a maven repository (`maven` subdirectory in repository) works, whereas including it via `dependencies.yml` fails.

A few more links are included in the README of the test repository.

The error appears to be something like the following: `nd4j-native` needs `nd4j-backend-impls`, but this package (https://repo.maven.apache.org/maven2/org/nd4j/nd4j-backend-impls/0.9.1/) only contains a POM and nothing else, whereas bazel-deps is searching for a specific jar?

**Comment by vmax** [comment]
@flyingsilverfin may be relevant https://github.com/johnynek/bazel-deps/pull/229

**Comment by flyingsilverfin** [comment]
@vmax This is solved so I'm closing it!
